=== peetkes/schema-validator/data/schemas/Release_A/schema/stop/1.2.1/imop-resources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/stop/imop/resources/" version="1.2.1"
  xmlns:data="https://standaarden.overheid.nl/stop/imop/data/"
  xmlns:tekst="https://standaarden.overheid.nl/stop/imop/tekst/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation source="https://koop.gitlab.io/lvbb/lvbb-ozon/go/goto.html?to=stop&amp;id=xsd:rsc">"resources-schema" van STOP. </xs:documentation>
    <xs:documentation>Dit schema definieert de elementen voor de STOP-modules voor resources</xs:documentation>
    <xs:documentation>versie 1.2.1</xs:documentation>
  </xs:annotation>
  
  <xs:element name="Waardelijst">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:WaardelijstInfo" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="rsc:Waarde" />
      </xs:sequence>
      <xs:attributeGroup ref="rsc:agSchemaVersie" />
    </xs:complexType>
  </xs:element>

  <xs:element name="WaardelijstInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:uitbreidbaar" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:versie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Waarde">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigVanaf" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigTot" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     Eigenschappen                             
  ================================================ 
  -->
  <xs:element name="eindverantwoordelijke" type="rsc:dtResourceRef" />
  <xs:element name="url" type="xs:anyURI" />
  <xs:element name="uitbreidbaar" type="xs:boolean" />
  <xs:element name="versie" type="xs:token"/>
  <xs:element name="geldigVanaf" type="xs:date" />
  <xs:element name="geldigTot" type="xs:date" />
  <xs:element name="id" type="rsc:dtResourceRef" />
  <xs:element name="label" type="xs:token" />
  <xs:element name="beschrijving" type="xs:token" />
  
  <xs:element name="vindplaatsen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:heeftVindplaats" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="heeftVindplaats">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:Vindplaats" maxOccurs="1" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vindplaats">
    <xs:complexType>
      <xs:all>
        <xs:element ref="rsc:url" />
        <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     model groups en datatypes                         
  ================================================ 
  -->
  <xs:group name="mgResource">
    <xs:sequence>
      <xs:element ref="rsc:id" />
      <xs:element ref="rsc:label" />
      <xs:element maxOccurs="1" minOccurs="0" ref="rsc:beschrijving" />
      <xs:element minOccurs="0" ref="rsc:vindplaatsen" />
      <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="dtResourceRef">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:attributeGroup name="agSchemaVersie">
    <xs:attribute name="schemaversie" type="rsc:dtSchemaVersie" use="optional" />
  </xs:attributeGroup>
  
  <xs:simpleType name="dtSchemaVersie">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

</xs:schema>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten-extra/1.3.0/gemeente.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.0" xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/ https://standaarden.overheid.nl/stop/1.3.0/imop-resources.xsd" xmlns="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <WaardelijstInfo>
    <id>/tooi/def/class/Gemeente</id>
    <label>gemeente Gemeenten</label>
    <beschrijving>Alle extra gemeenten t.b.v. testen op ETO en ACC</beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.1.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/tooi/id/gemeente/gm9901</id>
    <label>gemeente TST_01</label>
    <beschrijving>Gemeente TST_01</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9901</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9902</id>
    <label>gemeente TST_02</label>
    <beschrijving>Gemeente TST_02</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9902</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9903</id>
    <label>gemeente TST_03</label>
    <beschrijving>Gemeente TST_03</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9903</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9904</id>
    <label>gemeente TST_04</label>
    <beschrijving>Gemeente TST_04</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9904</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9905</id>
    <label>gemeente TST_05</label>
    <beschrijving>Gemeente TST_05</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9905</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9906</id>
    <label>gemeente TST_06</label>
    <beschrijving>Gemeente TST_06</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9906</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9907</id>
    <label>gemeente TST_07</label>
    <beschrijving>Gemeente TST_07</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9907</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9908</id>
    <label>gemeente TST_08</label>
    <beschrijving>Gemeente TST_08</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9908</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9909</id>
    <label>gemeente TST_09</label>
    <beschrijving>Gemeente TST_09</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9909</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9910</id>
    <label>gemeente TST_10</label>
    <beschrijving>Gemeente TST_10</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9910</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9911</id>
    <label>gemeente TST_11</label>
    <beschrijving>Gemeente TST_11</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9911</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9912</id>
    <label>gemeente TST_12</label>
    <beschrijving>Gemeente TST_12</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9912</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9913</id>
    <label>gemeente TST_13</label>
    <beschrijving>Gemeente TST_13</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9913</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9914</id>
    <label>gemeente TST_14</label>
    <beschrijving>Gemeente TST_14</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9914</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9915</id>
    <label>gemeente TST_15</label>
    <beschrijving>Gemeente TST_15</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9915</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9916</id>
    <label>gemeente TST_16</label>
    <beschrijving>Gemeente TST_16</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9916</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9917</id>
    <label>gemeente TST_17</label>
    <beschrijving>Gemeente TST_17</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9917</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9918</id>
    <label>gemeente TST_18</label>
    <beschrijving>Gemeente TST_18</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9918</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9919</id>
    <label>gemeente TST_19</label>
    <beschrijving>Gemeente TST_19</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9919</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9920</id>
    <label>gemeente TST_20</label>
    <beschrijving>Gemeente TST_20</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9920</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9921</id>
    <label>gemeente TST_21</label>
    <beschrijving>Gemeente TST_21</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9921</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9922</id>
    <label>gemeente TST_22</label>
    <beschrijving>Gemeente TST_22</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9922</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9923</id>
    <label>gemeente TST_23</label>
    <beschrijving>Gemeente TST_23</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9923</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9924</id>
    <label>gemeente TST_24</label>
    <beschrijving>Gemeente TST_24</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9924</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/tooi/id/gemeente/gm9925</id>
    <label>gemeente TST_25</label>
    <beschrijving>Gemeente TST_25</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/id/gemeente/gm9925</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.2/formaatinformatieobject.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.2"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.3.2/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/formaatinformatieobject</id>
    <label>Typering van informatieobjecten naar dataformaat</label>
    <beschrijving>De waardelijst beschrijft de typering van het informatieobject aan de hand van het
      technische uitwisselformaat zoals die door STOP ondersteund worden.</beschrijving>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/set/scw_stop_formaten_informatieobjecten</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.3.2</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/informatieobject/gio_002</id>
    <label>Geoinformatieobject</label>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_3aa96d08</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/informatieobject/doc_001</id>
    <label>PDF-document</label>
    <vindplaatsen>
      <heeftVindplaats>
        <Vindplaats>
          <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_75029aa4</url>
        </Vindplaats>
      </heeftVindplaats>
    </vindplaatsen>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.0/soortwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.0"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.0/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/join/id/stop/soortwork</id>
      <label>worktypes</label>
      <beschrijving>Alle worktypes zoals gedefinieerd in het Informatiemodel STOP</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/scw_stop_worktypes</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.0</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/join/id/stop/work_003</id>
      <label>Besluit</label>
      <beschrijving>Een generiek besluit</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_2307a3ff</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_005</id>
      <label>Geconsolideerd informatieobject</label>
      <beschrijving>Consolidatie van een informatieobject</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_46a1f04c</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_006</id>
      <label>Geconsolideerde regeling</label>
      <beschrijving>Consolidatie van een Regeling</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_1c4446cb</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_010</id>
      <label>Informatieobject</label>
      <beschrijving>Een informatieobject. Het formaat van het informatieobject wordt vastgelegd
         middels waardenlijst /join/id/stop/formaatinformatieobject. </beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_ea80bf73</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_015</id>
      <label>Officiële Publicatie</label>
      <beschrijving>Officiële publicatie. Verdere typering van officiele publicaties wordt
         vastgelegd middels waardelijst /join/id/stop/soortpublicatie.</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_89625c86</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_018</id>
      <label>Rectificatie</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_cb739009</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_019</id>
      <label>Regeling</label>
      <beschrijving>Een Regeling. Verdere typering van regelingen wordt vastgelegd middels
         waardelijst /join/id/stop/soortregeling.</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_840059b4</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_021</id>
      <label>Tijdelijk regelingdeel</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_59e0259b</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_022</id>
      <label>Consolidatie van een tijdelijk regelingdeel</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_43d8e132</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_023</id>
      <label>Kennisgeving</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_64981328</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/work_024</id>
      <label>Versieinformatie</label>
      <beschrijving>Alleen voor gebruik in een Uitwisselingspakket. Bevat versieinformatie over de
         andere componenten in een uitwisselingspakket.</beschrijving>
     <vindplaatsen>
       <heeftVindplaats>
         <Vindplaats>
           <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_7e7d6677</url>
         </Vindplaats>
       </heeftVindplaats>
     </vindplaatsen>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.1.0/soortprocedure.xml
<?xml version="1.0" encoding="utf-8"?>
<Waardelijst schemaversie="1.1.0"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.1.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/soortprocedure</id>
    <label>Besluitvormingsprocedures</label>
    <beschrijving>De waardelijst beschrijft onderkende besluitvormingsprocedures.</beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.1.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/proceduretype_ontwerp</id>
    <label>Ontwerpbesluit</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/proceduretype_definitief</id>
    <label>Definitief besluit</label>
  </Waarde>
</Waardelijst>
