=== peetkes/schema-validator/data/schemas/Release_A/schema/stop/1.2.1/imop-resources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/stop/imop/resources/" version="1.2.1"
  xmlns:data="https://standaarden.overheid.nl/stop/imop/data/"
  xmlns:tekst="https://standaarden.overheid.nl/stop/imop/tekst/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation source="https://koop.gitlab.io/lvbb/lvbb-ozon/go/goto.html?to=stop&amp;id=xsd:rsc">"resources-schema" van STOP. </xs:documentation>
    <xs:documentation>Dit schema definieert de elementen voor de STOP-modules voor resources</xs:documentation>
    <xs:documentation>versie 1.2.1</xs:documentation>
  </xs:annotation>
  
  <xs:element name="Waardelijst">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:WaardelijstInfo" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="rsc:Waarde" />
      </xs:sequence>
      <xs:attributeGroup ref="rsc:agSchemaVersie" />
    </xs:complexType>
  </xs:element>

  <xs:element name="WaardelijstInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:uitbreidbaar" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:versie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Waarde">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigVanaf" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigTot" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     Eigenschappen                             
  ================================================ 
  -->
  <xs:element name="eindverantwoordelijke" type="rsc:dtResourceRef" />
  <xs:element name="url" type="xs:anyURI" />
  <xs:element name="uitbreidbaar" type="xs:boolean" />
  <xs:element name="versie" type="xs:token"/>
  <xs:element name="geldigVanaf" type="xs:date" />
  <xs:element name="geldigTot" type="xs:date" />
  <xs:element name="id" type="rsc:dtResourceRef" />
  <xs:element name="label" type="xs:token" />
  <xs:element name="beschrijving" type="xs:token" />
  
  <xs:element name="vindplaatsen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:heeftVindplaats" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="heeftVindplaats">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:Vindplaats" maxOccurs="1" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vindplaats">
    <xs:complexType>
      <xs:all>
        <xs:element ref="rsc:url" />
        <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     model groups en datatypes                         
  ================================================ 
  -->
  <xs:group name="mgResource">
    <xs:sequence>
      <xs:element ref="rsc:id" />
      <xs:element ref="rsc:label" />
      <xs:element maxOccurs="1" minOccurs="0" ref="rsc:beschrijving" />
      <xs:element minOccurs="0" ref="rsc:vindplaatsen" />
      <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="dtResourceRef">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:attributeGroup name="agSchemaVersie">
    <xs:attribute name="schemaversie" type="rsc:dtSchemaVersie" use="optional" />
  </xs:attributeGroup>
  
  <xs:simpleType name="dtSchemaVersie">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

</xs:schema>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.0/soortregeling.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.0"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.0/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/join/id/stop/soortregeling</id>
      <label>Typering van regelingen</label>
      <beschrijving>De waardelijst beschrijft de regelingtypen die door STOP onderkend worden. Dat
         is inclusief domein-specifieke besluiten uit in toepassingsprofielen voor zover het
         onderscheiden daarvan het STOP domein raakt. Dat laatste is bijvoorbeeld het geval als
         bepaalde tijdstempels van rechtswege bepaald worden.</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/ccw_stop_regelingsoorten_tpod</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.0</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/join/id/stop/regelingtype_001</id>
      <label>AMvB</label>
      <beschrijving>Algemene Maatregel van Bestuur</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_964af97a</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_002</id>
      <label>MinisteriÃ«le Regeling</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_d2a6707c</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_003</id>
      <label>Omgevingsplan</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_0887da8f</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_004</id>
      <label>Omgevingsverordening</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_c30d04d4</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_005</id>
      <label>Waterschapsverordening</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_84a23404</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_006</id>
      <label>Omgevingsvisie</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_0776061d</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_007</id>
      <label>Projectbesluit</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_c74a0781</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_008</id>
      <label>Instructie</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_8f68c804</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_009</id>
      <label>Voorbeschermingsregels</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_5cbd74c8</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_010</id>
      <label>Programma</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_3f4ec90d</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_011</id>
      <label>Reactieve interventie</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_9757fbcf</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_012</id>
      <label>Aanwijzingsbesluit N2000</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_6b572c33</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_013</id>
      <label>Toegangsbeperkingsbesluit</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_5bea6262</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_014</id>
      <label>Omgevingsplanregels Projectbesluit</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_cd480cce</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_015</id>
      <label>Voorbeschermingsregels Omgevingsplan</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_8226285b</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/regelingtype_016</id>
      <label>Voorbeschermingsregels Omgevingsverordening</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_526e0a9f</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten-extra/1.1.0/provincie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.1.0" xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/ https://standaarden.overheid.nl/stop/1.1.0/imop-resources.xsd" xmlns="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <WaardelijstInfo>
    <id>/tooi/def/class/Provincie</id>
    <label>Provincies</label>
    <beschrijving>Alle extra provincies tbv testen op ACC en ETO</beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.1.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/tooi/id/provincie/pv61</id>
    <label>provincie TST_01</label>
    <beschrijving>Provincie TST_01</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv62</id>
    <label>provincie TST_02</label>
    <beschrijving>Provincie TST_02</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv63</id>
    <label>provincie TST_03</label>
    <beschrijving>Provincie TST_03</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv64</id>
    <label>provincie TST_04</label>
    <beschrijving>Provincie TST_04</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv65</id>
    <label>provincie TST_05</label>
    <beschrijving>Provincie TST_05</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv66</id>
    <label>provincie TST_06</label>
    <beschrijving>Provincie TST_06</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv67</id>
    <label>provincie TST_07</label>
    <beschrijving>Provincie TST_07</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv68</id>
    <label>provincie TST_08</label>
    <beschrijving>Provincie TST_08</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv69</id>
    <label>provincie TST_09</label>
    <beschrijving>Provincie TST_09</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv70</id>
    <label>provincie TST_10</label>
    <beschrijving>Provincie TST_10</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv71</id>
    <label>provincie TST_11</label>
    <beschrijving>Provincie TST_11</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv72</id>
    <label>provincie TST_12</label>
    <beschrijving>Provincie TST_12</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv73</id>
    <label>provincie TST_13</label>
    <beschrijving>Provincie TST_13</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv74</id>
    <label>provincie TST_14</label>
    <beschrijving>Provincie TST_14</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv75</id>
    <label>provincie TST_15</label>
    <beschrijving>Provincie TST_15</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv76</id>
    <label>provincie TST_16</label>
    <beschrijving>Provincie TST_16</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv77</id>
    <label>provincie TST_17</label>
    <beschrijving>Provincie TST_17</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv78</id>
    <label>provincie TST_18</label>
    <beschrijving>Provincie TST_18</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv79</id>
    <label>provincie TST_19</label>
    <beschrijving>Provincie TST_19</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv80</id>
    <label>provincie TST_20</label>
    <beschrijving>Provincie TST_20</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv81</id>
    <label>provincie TST_21</label>
    <beschrijving>Provincie TST_21</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv82</id>
    <label>provincie TST_22</label>
    <beschrijving>Provincie TST_22</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv83</id>
    <label>provincie TST_23</label>
    <beschrijving>Provincie TST_23</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv84</id>
    <label>provincie TST_24</label>
    <beschrijving>Provincie TST_24</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv85</id>
    <label>provincie TST_25</label>
    <beschrijving>Provincie TST_25</beschrijving>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.2.0/provincie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.2.0" xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/ https://standaarden.overheid.nl/stop/1.2.0/imop-resources.xsd" xmlns="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <WaardelijstInfo>
    <id>/tooi/def/class/Provincie</id>
    <label>Provincies</label>
    <beschrijving>Alle provincies uit GRS </beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.2.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/tooi/id/provincie/pv22</id>
    <label>provincie Drenthe</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv24</id>
    <label>provincie Flevoland</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv21</id>
    <label>provincie Frysl√¢n</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv25</id>
    <label>provincie Gelderland</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv20</id>
    <label>provincie Groningen</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv31</id>
    <label>provincie Limburg</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv30</id>
    <label>provincie Noord-Brabant</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv27</id>
    <label>provincie Noord-Holland</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv23</id>
    <label>provincie Overijssel</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv26</id>
    <label>provincie Utrecht</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv29</id>
    <label>provincie Zeeland</label>
  </Waarde>
  <Waarde>
    <id>/tooi/id/provincie/pv28</id>
    <label>provincie Zuid-Holland</label>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.2.0/bekendmakingsblad.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.2.0"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.2.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/bekendmakingsblad</id>
    <label>bekendmakingsblad</label>
    <beschrijving>officiÃ«le bekendmakingsbladen. Deze sublijst is in TOOI beschikbaar als
      /tooi/def/concept/c_c392702e</beschrijving>
    <uitbreidbaar>false</uitbreidbaar>
    <versie>1.2.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/tooi/def/concept/c_61e3099a</id>
    <label>Staatsblad</label>
    <beschrijving>Stb</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_0670bae1</id>
    <label>Staatscourant</label>
    <beschrijving>Stcrt</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_bdc265d5</id>
    <label>Provinciaal blad</label>
    <beschrijving>Prb</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_b3179555</id>
    <label>Tractatenblad</label>
    <beschrijving>Trb</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_81cc2eb5</id>
    <label>Gemeenteblad</label>
    <beschrijving>Gmb</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_c97b118a</id>
    <label>Waterschapsblad</label>
    <beschrijving>Wsb</beschrijving>
  </Waarde>
  <Waarde>
    <id>/tooi/def/concept/c_12cd7b9b</id>
    <label>Blad gemeenschappelijke regeling</label>
    <beschrijving>Bgr</beschrijving>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.2/waterschap.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.2"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.2/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/tooi/def/class/Waterschap</id>
      <label>Waterschappen</label>
      <beschrijving>Alle waterschappen uit GRS </beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/rwc_waterschappen_compleet</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.2</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/tooi/id/waterschap/ws0654</id>
      <label>waterschap Aa en Maas</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0654</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0155</id>
      <label>waterschap Amstel, Gooi en Vecht</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0155</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0652</id>
      <label>waterschap Brabantse Delta</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0652</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0539</id>
      <label>waterschap De Dommel</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0539</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0664</id>
      <label>waterschap Drents Overijsselse Delta</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0664</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0655</id>
      <label>waterschap Hollandse Delta</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0655</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0636</id>
      <label>Hoogheemraadschap De Stichtse Rijnlanden</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0636</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0651</id>
      <label>Hoogheemraadschap Hollands Noorderkwartier</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0651</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0372</id>
      <label>Hoogheemraadschap van Delfland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0372</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0616</id>
      <label>Hoogheemraadschap van Rijnland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0616</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0656</id>
      <label>Hoogheemraadschap van Schieland en de Krimpenerwaard</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0656</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0646</id>
      <label>waterschap Hunze en Aa's</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0646</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0647</id>
      <label>waterschap Noorderzijlvest</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0647</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0152</id>
      <label>waterschap Rijn en IJssel</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0152</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0621</id>
      <label>waterschap Rivierenland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0621</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0661</id>
      <label>waterschap Scheldestromen</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0661</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0662</id>
      <label>waterschap Vallei en Veluwe</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0662</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0663</id>
      <label>waterschap Vechtstromen</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0663</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0665</id>
      <label>waterschap Limburg</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0665</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0653</id>
      <label>Wetterskip Frysl√¢n</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0653</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/waterschap/ws0650</id>
      <label>waterschap Zuiderzeeland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/waterschap/ws0650</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
</Waardelijst>
