=== peetkes/schema-validator/data/schemas/Release_A/schema/stop/1.2.1/imop-resources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/stop/imop/resources/" version="1.2.1"
  xmlns:data="https://standaarden.overheid.nl/stop/imop/data/"
  xmlns:tekst="https://standaarden.overheid.nl/stop/imop/tekst/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation source="https://koop.gitlab.io/lvbb/lvbb-ozon/go/goto.html?to=stop&amp;id=xsd:rsc">"resources-schema" van STOP. </xs:documentation>
    <xs:documentation>Dit schema definieert de elementen voor de STOP-modules voor resources</xs:documentation>
    <xs:documentation>versie 1.2.1</xs:documentation>
  </xs:annotation>
  
  <xs:element name="Waardelijst">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:WaardelijstInfo" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="rsc:Waarde" />
      </xs:sequence>
      <xs:attributeGroup ref="rsc:agSchemaVersie" />
    </xs:complexType>
  </xs:element>

  <xs:element name="WaardelijstInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:uitbreidbaar" />
        <xs:element minOccurs="1" maxOccurs="1" ref="rsc:versie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Waarde">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="rsc:mgResource" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigVanaf" />
        <xs:element maxOccurs="1" minOccurs="0" ref="rsc:geldigTot" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     Eigenschappen                             
  ================================================ 
  -->
  <xs:element name="eindverantwoordelijke" type="rsc:dtResourceRef" />
  <xs:element name="url" type="xs:anyURI" />
  <xs:element name="uitbreidbaar" type="xs:boolean" />
  <xs:element name="versie" type="xs:token"/>
  <xs:element name="geldigVanaf" type="xs:date" />
  <xs:element name="geldigTot" type="xs:date" />
  <xs:element name="id" type="rsc:dtResourceRef" />
  <xs:element name="label" type="xs:token" />
  <xs:element name="beschrijving" type="xs:token" />
  
  <xs:element name="vindplaatsen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:heeftVindplaats" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="heeftVindplaats">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rsc:Vindplaats" maxOccurs="1" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Vindplaats">
    <xs:complexType>
      <xs:all>
        <xs:element ref="rsc:url" />
        <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!--
  ================================================ 
     model groups en datatypes                         
  ================================================ 
  -->
  <xs:group name="mgResource">
    <xs:sequence>
      <xs:element ref="rsc:id" />
      <xs:element ref="rsc:label" />
      <xs:element maxOccurs="1" minOccurs="0" ref="rsc:beschrijving" />
      <xs:element minOccurs="0" ref="rsc:vindplaatsen" />
      <xs:element minOccurs="0" ref="rsc:eindverantwoordelijke" />
    </xs:sequence>
  </xs:group>

  <xs:simpleType name="dtResourceRef">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

  <xs:attributeGroup name="agSchemaVersie">
    <xs:attribute name="schemaversie" type="rsc:dtSchemaVersie" use="optional" />
  </xs:attributeGroup>
  
  <xs:simpleType name="dtSchemaVersie">
    <xs:restriction base="xs:token" />
  </xs:simpleType>

</xs:schema>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.2.0/formaatinformatieobject.xml
<?xml version="1.0" encoding="utf-8"?>
<Waardelijst schemaversie="1.2.0"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.2.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/formaatinformatieobject</id>
    <label>Typering van informatieobjecten naar dataformaat</label>
    <beschrijving>De waardelijst beschrijft de typering van het informatieobject aan de hand van het
      technische uitwisselformaat zoals die door STOP ondersteund worden.</beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.2.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/informatieobject/gio_002</id>
    <label>Geoinformatieobject</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/informatieobject/doc_001</id>
    <label>PDF-document</label>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.2/provincie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.2"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.2/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/tooi/def/class/Provincie</id>
      <label>Provincies</label>
      <beschrijving>Alle provincies uit GRS </beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/rwc_provincies_compleet</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.2</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/tooi/id/provincie/pv22</id>
      <label>provincie Drenthe</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv22</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv24</id>
      <label>provincie Flevoland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv24</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv21</id>
      <label>provincie Frysl√¢n</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv21</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv25</id>
      <label>provincie Gelderland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv25</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv20</id>
      <label>provincie Groningen</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv20</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv31</id>
      <label>provincie Limburg</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv31</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv30</id>
      <label>provincie Noord-Brabant</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv30</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv27</id>
      <label>provincie Noord-Holland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv27</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv23</id>
      <label>provincie Overijssel</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv23</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv26</id>
      <label>provincie Utrecht</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv26</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv29</id>
      <label>provincie Zeeland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv29</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/id/provincie/pv28</id>
      <label>provincie Zuid-Holland</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/id/provincie/pv28</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/2.0.0/procedurestap_ontwerp.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
             xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/       https://standaarden.overheid.nl/stop/2.0.0/imop-resources.xsd"
             schemaversie="2.0.0">
   <WaardelijstInfo>
      <id>/join/id/stop/procedure/ontwerpbesluit</id>
      <label>Stappen uit de besluitvormingsprocedure voor een ontwerpbesluit</label>
      <beschrijving>De waardelijst beschrijft de stappen die gezet kunnen worden als onderdeel van een
      besluitvormingsprocedure voor een ontwerpbesluit. De waardelijst beschrijft alleen de stappen
      vanaf de vaststelling van een besluit. Sommige waarden uit deze lijst komen ook voor in
      /join/id/stop/procedure/definitiefbesluit</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/ccw_stop_stappen_besluitvorming_ontwerpbesluit</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>2.0.0</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/join/id/stop/procedure/stap_002</id>
      <label>Vaststelling</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_641ecd76</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/procedure/stap_003</id>
      <label>Ondertekening</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_e1ec050e</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/procedure/stap_004</id>
      <label>Publicatie</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_932b7730</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/procedure/stap_005</id>
      <label>Einde inzagetermijn</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_1c457490</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/procedure/stap_014</id>
      <label>Begin inzagetermijn</label>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_dad20b4a</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.0/soortpublicatie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.0"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.0/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/join/id/stop/soortpublicatie</id>
      <label>Typering van publicaties</label>
      <beschrijving>De waardelijst beschrijft de typering van officiÃ«le publicaties</beschrijving>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.0</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/join/id/stop/soortpublicatie_001</id>
      <label>Bekendmaking</label>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/soortpublicatie_002</id>
      <label>Kennisgeving</label>
   </Waarde>
   <Waarde>
      <id>/join/id/stop/soortpublicatie_003</id>
      <label>Rectificatie</label>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.3.2/bestuursorgaan.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.3.2"
   xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
   https://standaarden.overheid.nl/stop/1.3.2/imop-resources.xsd">
   <WaardelijstInfo>
      <id>/tooi/def/class/Bestuursorgaan</id>
      <label>Bestuursorganen</label>
      <beschrijving>Alle bestuursorganen die van belang zijn voor de Omgevingswet</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/set/ccw_stop_bestuursorganen</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
      <uitbreidbaar>0</uitbreidbaar>
      <versie>1.3.2</versie>
   </WaardelijstInfo>
   <Waarde>
      <id>/tooi/def/thes/kern/c_2c4e7407</id>
      <label>burgemeester</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan gemeente
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_2a1d64e7)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_2c4e7407</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_28ecfd6d</id>
      <label>college van burgemeester en wethouders</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan gemeente
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_2a1d64e7)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_28ecfd6d</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_2a7d8663</id>
      <label>gemeenteraad</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan gemeente
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_2a1d64e7)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_2a7d8663</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_e24d39f6</id>
      <label>commissaris van de Koning</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan provincie
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_3469893d)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_e24d39f6</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_61676cbc</id>
      <label>gedeputeerde staten</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan provincie
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_3469893d)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_61676cbc</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_411b4e4a</id>
      <label>provinciale staten</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan provincie
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_3469893d)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_411b4e4a</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_bcfb7b4e</id>
      <label>minister</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan staat
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_e3cf586b)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_bcfb7b4e</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_91fb5e42</id>
      <label>regering</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan staat
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_e3cf586b)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_91fb5e42</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_3aaa4d12</id>
      <label>staatssecretaris</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan staat
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_e3cf586b)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_3aaa4d12</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_70c87e3d</id>
      <label>algemeen bestuur</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan waterschap
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_be4c3d94)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_70c87e3d</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_5cc92c89</id>
      <label>dagelijks bestuur</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan waterschap
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_be4c3d94)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_5cc92c89</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
   <Waarde>
      <id>/tooi/def/thes/kern/c_f70a6113</id>
      <label>dijkgraaf</label>
      <beschrijving>Behoort tot de groep: bestuursorgaan waterschap
         (https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_be4c3d94)</beschrijving>
      <vindplaatsen>
         <heeftVindplaats>
            <Vindplaats>
               <url>https://identifier.overheid.nl/tooi/def/thes/kern/c_f70a6113</url>
            </Vindplaats>
         </heeftVindplaats>
      </vindplaatsen>
   </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.1.0/procedurestap_ontwerp.xml
<?xml version="1.0" encoding="utf-8"?>
<Waardelijst schemaversie="1.1.0"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.1.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/procedure/ontwerpbesluit</id>
    <label>Stappen uit de besluitvormingsprocedure voor een ontwerpbesluit</label>
    <beschrijving>De waardelijst beschrijft de stappen die gezet kunnen worden als onderdeel van een
      besluitvormingsprocedure voor een ontwerpbesluit. De waardelijst beschrijft alleen de stappen
      vanaf de vaststelling van een besluit. Sommige waarden uit deze lijst komen ook voor in
      /join/id/stop/procedure/definitiefbesluit</beschrijving>
    <uitbreidbaar>false</uitbreidbaar>
    <versie>1.1.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/procedure/stap_002</id>
    <label>Vaststelling</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_003</id>
    <label>Ondertekening</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_004</id>
    <label>Publicatie</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_005</id>
    <label>Einde inzagetermijn</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_014</id>
    <label>Begin inzagetermijn</label>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.2.0/procedurestap_definitief.xml
<?xml version="1.0" encoding="utf-8"?>
<Waardelijst schemaversie="1.2.0" xmlns="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.2.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/procedure/definitiefbesluit</id>
    <label>Stappen uit de besluitvormingsprocedure voor een definitief besluit</label>
    <beschrijving>De waardelijst beschrijft de stappen die gezet kunnen worden als onderdeel van een
      besluitvormingsprocedure voor een definitief besluit. De waardelijst beschrijft alleen de
      stappen vanaf de vaststelling van een besluit. De waarden komen overeen met
      /join/id/stop/procedure/ontwerpbesluit</beschrijving>
    <uitbreidbaar>false</uitbreidbaar>
    <versie>@@@VERSIES@@@</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/procedure/stap_002</id>
    <label>Vaststelling</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_003</id>
    <label>Ondertekening</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_004</id>
    <label>Publicatie</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_015</id>
    <label>Einde bezwaartermijn</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_016</id>
    <label>Einde beroepstermijn</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_018</id>
    <label>Beroep(en) ingesteld</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_019</id>
    <label>Schorsing</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_020</id>
    <label>Schorsing opgeheven</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/procedure/stap_021</id>
    <label>Beroep(en) definitief afgedaan</label>
  </Waarde>
</Waardelijst>

=== peetkes/schema-validator/data/waardelijsten/Release_A/waardelijsten/1.1.0/soortwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<Waardelijst schemaversie="1.1.0"
  xmlns="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:rsc="https://standaarden.overheid.nl/stop/imop/resources/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/resources/
  https://standaarden.overheid.nl/stop/1.1.0/imop-resources.xsd">
  <WaardelijstInfo>
    <id>/join/id/stop/soortwork</id>
    <label>worktypes</label>
    <beschrijving>Alle worktypes zoals gedefinieerd in het Informatiemodel STOP</beschrijving>
    <uitbreidbaar>0</uitbreidbaar>
    <versie>1.1.0</versie>
  </WaardelijstInfo>
  <Waarde>
    <id>/join/id/stop/work_003</id>
    <label>Besluit</label>
    <beschrijving>Een generiek besluit</beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_005</id>
    <label>Geconsolideerd informatieobject</label>
    <beschrijving>Consolidatie van een informatieobject</beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_006</id>
    <label>Geconsolideerde regeling</label>
    <beschrijving>Consolidatie van een Regeling</beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_010</id>
    <label>Informatieobject</label>
    <beschrijving>Een informatieobject. Het formaat van het informatieobject wordt vastgelegd
      middels waardenlijst /join/id/stop/formaatinformatieobject. </beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_015</id>
    <label>Officiële Publicatie</label>
    <beschrijving>Officiële publicatie. Verdere typering van officiele publicaties wordt vastgelegd
      middels waardelijst /join/id/stop/soortpublicatie.</beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_018</id>
    <label>Rectificatie</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_019</id>
    <label>Regeling</label>
    <beschrijving>Een Regeling. Verdere typering van regelingen wordt vastgelegd middels waardelijst
      /join/id/stop/soortregeling.</beschrijving>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_021</id>
    <label>Tijdelijk regelingdeel</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_022</id>
    <label>Consolidatie van een tijdelijk regelingdeel</label>
  </Waarde>
  <Waarde>
    <id>/join/id/stop/work_023</id>
    <label>Kennisgeving</label>
  </Waarde>
</Waardelijst>
